### ISSUE TITLE
[lspconfig] Cannot access configuration for `server`

### ISSUE THREAD

**Issue by wesleyjrz** [dundalek/lazy-lsp.nvim#13]
I don't know why, but every time I open Neovim after installing this plugin I get the following error (doesn't matter what type of file I'm opening):

```
[lspconfig] Cannot access configuration for docker_compose_language_service. Ensure this server is listed in `server_configurations.md` or added as a custom server.
[lspconfig] Cannot access configuration for docker_compose_language_service. Ensure this server is listed in `server_configurations.md` or added as a custom server.
Error in packer_compiled: ...pack/packer/start/lazy-lsp.nvim/lua/lazy-lsp/helpers.lua:16: attempt to index field 'document_config' (a nil value)
Please check your config for correctness
```

And it always shows a different server name that it cannot access the configuration.

I'm running Neovim v0.8.1 on NixOS 22.11 with the `2023.02.27` version of the plugin, I've already tested it with Neovim Nightly or using the master branch, but I've got the same errors.

Here's my configuration:

```lua
require("lazy-lsp").setup {
	excluded_servers = {
		-- prefer ccls
		"clangd",
	},

	-- Default options
	default_config = {
		on_attach = on_attach,
	},

	-- Custom options
	configs = {
		sumneko_lua = {
			cmd = { "lua-language-server" },
			settings = {
				Lua = {
					runtime = {
						version = "LuaJIT",
						path = sumneko_runtime_path
					},
					diagnostics = {
						disable = { "codestyle-check", "spell-check" },
						globals = { "vim", "use", "require" }
					},
					completion = {
						enable = true,
						callSnippet = "Disable",
						keywordSnippet = "Disable"
					},
					format = { enable = false },
					hint = { enable = false },
					hover = { enable = false },
					workspace = {
						checkThirdParty = true,
						library = vim.api.nvim_get_runtime_file("", true)
					},
					telemetry = { enable = false }
				}
			}
		},
		pyright = {
			python = {
				analysis = {
					autoSearchPaths = true,
					diagnosticMode = "workspace",
					useLibraryCodeForTypes = true
				}
			}
		}
	}
}
```

**Comment by dundalek** [comment]
Thanks for the report. I think this might be because you have an older version of [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig). Updating your plugins (e.g. `:PackerSync` for packer) should help.

Sidenote: In this instance we don't actually have nix pkg for `docker_compose_language_service` specified, so we should not even try it which would avoid the error message. I should be able to push a fix to improve that.

**Comment by wesleyjrz** [comment]
> Thanks for the report. I think this might be because you have an older version of [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig). Updating your plugins (e.g. `:PackerSync` for packer) should help.
> 
> Sidenote: In this instance we don't actually have nix pkg for `docker_compose_language_service` specified, so we should not even try it which would avoid the error message. I should be able to push a fix to improve that.

Thank you. I was using the latest release of lspconfig, it should also be clear on the documentation that it currently don't work with the latest release.

Now it seems to be working (at least for Python, C and C++), but I've an error with lua:

```
Client 1 quit with exit code 1 and signal 0
```

I looked at `:LspInfo` and the plugin is using the command `nix-shell -p lua-language-server --run 'lua-language-server`, but the package name on nixpkgs is `sumneko-lua-language-server`, so the correct command would be `nix-shell -p sumneko-lua-language-server --run 'lua-language-server`.

**Comment by wesleyjrz** [comment]
Sorry, I've just noticed that the package was renamed to `lua-language-server` on the unstable channel. I will add the unstable channel until it updates on stable, it would be nice to have an option to change the package name on the configuration.

**Comment by dundalek** [comment]
> Sorry, I've just noticed that the package was renamed to `lua-language-server` on the unstable channel. I will add the unstable channel until it updates on stable,

That's a great catch, I just use unstable so it didn't occur to me that different channel could cause issues like that. I find unstable works best for dev tooling to keep up with latest changes, could probably add a mention/reccomendation to the readme.

> it would be nice to have an option to change the package name on the configuration.

This came up before, I opened a new issue https://github.com/dundalek/lazy-lsp.nvim/issues/15 to collect thoughts and make a decision about it.
