### ISSUE TITLE
Consider upgrading `clangd` to version 16

### ISSUE THREAD

**Issue by metiulekm** [dundalek/lazy-lsp.nvim#21]
The package used is `clang-tools`, which provides version 14 of `clangd`, but the newest version is actually version 16, packaged as `clang-tools_16` in nixpkgs. This upgrade can useful, for example <https://github.com/lvimuser/lsp-inlayhints.nvim> expects at least version 15.

Of course, this would require manually tracking the newest version of `clang-tools` in nixpkgs, which could be quite annoying.

**Comment by dundalek** [comment]
Sounds good to me, version 16 seems even available in 22.11 channel. We can bump it again in the future when someone notices 16 is obsolete like 14 currently is :) It is curious why nixpkgs did not bump it already, it does not seem LLVM has notion of LTS releases or anything.
