### ISSUE TITLE
Add an option to disable notification warnings

### ISSUE THREAD

**Issue by ruanyouxing** [dundalek/lazy-lsp.nvim#24]
I know registering LSPs into `nix-shell` environment is a great idea but it still has latency (maybe 4 or 5 seconds). In those seconds the lspconfig will show out this warning
![image](https://github.com/dundalek/lazy-lsp.nvim/assets/87190231/aa755d5f-210b-438f-b80d-0af1ebbdac73)
(Even I tried to exit neovim and open it again several times but this warning still poped up)
That's feel annoying to me or anyone will use this plugin in the future, so I think you should add an option to disable these warnings, or manage to download the LSP via nix then call lspconfig after, thanks.

**Comment by dundalek** [comment]
This looks like some lsp server might be misbehaving. What file type are you trying to open? It would be useful to see outputs of `:LspInfo` or `:LspLog`.

Also what plugin are you using for notifications?

**Comment by ruanyouxing** [comment]
> This looks like some lsp server might be misbehaving. What file type are you trying to open? It would be useful to see outputs of `:LspInfo` or `:LspLog`.
> 
> Also what plugin are you using for notifications?

It's an Javascript file (Rust has the same issue) and I'm using [nvim-notify](https://github.com/rcarriga/nvim-notify) for my notifications
`:LspLog` should look like this
```
[START][2023-07-10 07:27:30] LSP logging initiated
[ERROR][2023-07-10 07:27:30] .../vim/lsp/rpc.lua:734	"rpc"	"/nix/var/nix/profiles/default/bin/nix-shell"	"stderr"	"flags/invalid ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
[ERROR][2023-07-10 07:27:30] .../vim/lsp/rpc.lua:734	"rpc"	"/nix/var/nix/profiles/default/bin/nix-shell"	"stderr"	"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n  × Failed to parse CLI arguments.\n    \n    Caused by:\n      No such command or positional: `lsp_proxy`, did you mean `lsp-proxy`?\n  \n\n"
```
Nothing special with `:LspInfo` I guess
![image](https://github.com/dundalek/lazy-lsp.nvim/assets/87190231/c80cdbb4-30c8-4fdc-bb0c-0cb84ba2b745)

**Comment by dundalek** [comment]
From the logs the relevant part seems to be "No such command or positional: `lsp_proxy`, did you mean `lsp-proxy`", which means the configuration is passing `lsp_proxy` parameter, but the server only understands `lsp-proxy`. When I searched in `nvim-lspconfig` repo I discovered that [rome](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/rome.lua#L5) has `lsp-proxy` parameter, so it seems your plugins might be out-of-date.

I would suggest updating your `nvim-lspconfig` plugin. Alternatively you could disable the rome server with `excluded_servers = { "rome" }`.

For Rust it might be a different issue, so if you try to open a rust file and post a log again we can see.

**Comment by ruanyouxing** [comment]
```
[START][2023-07-10 21:41:23] LSP logging initiated
[ERROR][2023-07-10 21:41:23] .../vim/lsp/rpc.lua:734	"rpc"	"/nix/var/nix/profiles/default/bin/nix-shell"	"stderr"	"error:\n       … while calling the 'derivationStrict' builtin\n\n         at /builtin/derivation.nix:9:12: (source not available)\n\n       … while evaluating derivation 'shell'\n         whose name attribute is located at /nix/store/n4xbvfwli2f0sk9130k0yz0dd2jzj4jp-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:303:7\n\n       … while evaluating attribute 'buildInputs' of derivation 'shell'\n\n         at /nix/store/n4xbvfwli2f0sk9130k0yz0dd2jzj4jp-nixpkgs/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:350:7:\n\n          349|       depsHostHost                = lib.elemAt (lib.elemAt dependencies 1) 0;\n          350|       buildInputs                 = lib.elemAt (lib.elemAt dependencies 1) 1;\n             |       ^\n          351|       depsTargetTarget            = lib.elemAt (lib.elemAt dependencies 2) 0;\n\n       error: rls was discontinued upstream, use rust-analyzer instead\n"
```
Here's the log
But after I exclude `rls` out in lazy-lsp config like this below, no errors found
```lua
require('lazy-lsp').setup{
    excluded_servers = {'rome', 'rls'}
}
```

**Comment by dundalek** [comment]
Great, it looks like `rls` was removed from Nix, so I pushed change to remove it too: https://github.com/dundalek/lazy-lsp.nvim/commit/c35cb31854f87aece550404103d6ca921b2689aa

**Comment by dundalek** [comment]
To conclude warnings help to discover underlying issues with servers, so no plan to add an option to suppress them for now.
