### ISSUE TITLE
getting status of daemon socket access denied

### ISSUE THREAD

**Issue by Sveet-Pickle** [dundalek/lazy-lsp.nvim#27]
when i open any file that lazy lsp should work on, i get Client 2 quit with exit code 1 and signal 0.

when I run :LspLog I get:

error getting status of /nix/var/nix/daemon-socket/socket: Permission denied.

Im on Arch linux and installed nix from the Arch repository

**Comment by dundalek** [comment]
Hi, I don't use Arch, but from the wiki https://wiki.archlinux.org/title/Nix:

> 6.1 Permission denied
> Running nix repl or nix-env -u as user produces
> cannot connect to daemon at '/nix/var/nix/daemon-socket/socket: permission denied
> If you just installed nix, you need to reboot. 

Could you try to reboot?

**Comment by Sveet-Pickle** [comment]
reboot didn't fix the issue but I was able to figure out the problem. For whatever reason I wasn't given access permission/ownership at install so running a chown command on the nix install location fixed the problem.

**Comment by dundalek** [comment]
cool
