### ISSUE TITLE
Love it

### ISSUE THREAD

**Issue by Cloudef** [dundalek/lazy-lsp.nvim#28]
This really makes LSP experience on vim better. Wish someone did similar for syntax highlighting.

**Comment by dundalek** [comment]
Thanks!

For syntax highlighting you can install https://github.com/nvim-treesitter/nvim-treesitter which supports tons of languages. It is not lazy so it takes a some time to install and compile all the parsers upfront, but parser grammars have much smaller footprint than LSPs, so it works fine.
