### ISSUE TITLE
rust: add `cargo` and `rustfmt`?

### ISSUE THREAD

**Issue by fdietze** [dundalek/lazy-lsp.nvim#32]
Having a clean nixos system (no `cargo` etc installed) and opening a rust file in a rust project, `rust-analyzer` complains that it doesn't find `cargo`. Does it make sense to add it to the nix-shell? Same for `rustfmt`, which allows the lsp to format the buffer.

https://github.com/dundalek/lazy-lsp.nvim/blob/87305e02c8f167709598eea4b76542540d8366ff/lua/lazy-lsp/servers.lua#L234

I wanted to test this locally, but didn't get it working. I'm using lazy.nvim and edited the `servers.lua` file in the installed plugin, but didn't see any effect. Any hints?

**Comment by fdietze** [comment]
Another idea:
Many rust projects store their rust version and tooling in a [`rust-toolchain.toml`](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file). This can be read automatically by nix and produce a nix-shell with the right rust version and tooling installed: https://github.com/oxalica/rust-overlay

Not sure how practical that is in the scope of this nvim plugin.

**Comment by dundalek** [comment]
Thanks for the report. I pushed a fix https://github.com/dundalek/lazy-lsp.nvim/commit/e7638bd348c09c27f7fbcba758a6cd8aeca4ce37, please give it a try.

There were actually two things going on:
1. The [default lspconfig](https://github.com/neovim/nvim-lspconfig/blob/4bdd3800b4148f670c6cf55ef65f490148eeb550/lua/lspconfig/server_configurations/rust_analyzer.lua#L68) uses cargo to workspace path which fails even before nix-shell wrapper even runs. I added fallback with a simpler detection.
2. Added `cargo` and `rustfmt` dependencies to make sure things works properly once `rust-analyzer` starts.

**Comment by dundalek** [comment]
> Another idea: Many rust projects store their rust version and tooling in a [`rust-toolchain.toml`](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file). This can be read automatically by nix and produce a nix-shell with the right rust version and tooling installed: https://github.com/oxalica/rust-overlay
> 
> Not sure how practical that is in the scope of this nvim plugin.

Yeah, I am thinking if one uses special tooling that should be configured in user config.

**Comment by fdietze** [comment]
> Thanks for the report. I pushed a fix [e7638bd](https://github.com/dundalek/lazy-lsp.nvim/commit/e7638bd348c09c27f7fbcba758a6cd8aeca4ce37), please give it a try.

Works very well, thank you!

**Comment by dundalek** [comment]
Sweet, always great to get confirmation that it works on another computer, thanks!
