### ISSUE TITLE
Question: How to debug and/or customize version?

### ISSUE THREAD

**Issue by unphased** [dundalek/lazy-lsp.nvim#4]
I noticed that the clangd version that is provided is 11. When i was using clangd with coc.nvim it was auto-installing clangd 14. I would like to know what would be involved to customize/update something like this in this framework. I do not know anything about nix so the lack of documentation is a little challenging.

**Comment by dundalek** [comment]
It works by using the `clang-tools` nix package, which is at [version 14](https://search.nixos.org/packages?channel=22.11&from=0&size=50&sort=relevance&type=packages&query=clang-tools) for both stable (22.11) and unstable channels (channels are like distribution release versions).

You can verify which on which channels you are using with `nix-channel --list`, you will likely need to do an update with `nix-channel --update`. For more info about channels see the [docs](https://nixos.wiki/wiki/Nix_channels).

To verify you can run following: `nix-shell -p clang-tools --command "clangd --version"`
You will get the same version printed by the command inside neovim, for me it gives `clangd version 14.0.6`.

**Comment by dundalek** [comment]
@unphased Were you able to figure it out and get it working?

**Comment by dundalek** [comment]
Added a note about channels in https://github.com/dundalek/lazy-lsp.nvim/commit/c6593b96b1ede3f050621e3f5c070f581282f019
