### ISSUE TITLE
Add DAP servers

### ISSUE THREAD

**Issue by xyven1** [dundalek/lazy-lsp.nvim#41]
`Mason.nvim`, the main alternative to lazy-lsp, also has binaries for DAP servers, and along with `mason-nvim-dap` can provide a [default DAP adapters and configurations](https://github.com/jay-babu/mason-nvim-dap.nvim/tree/67210c0e775adec55de9826b038e8b62de554afc/lua/mason-nvim-dap/mappings). Bringing this to lazy-lsp would take it the next level, as it could replace all current features of the mason family of plugins. 

This would entail at least a couple of steps:
1) Create a list of [DAP servers](https://microsoft.github.io/debug-adapter-protocol/implementors/adapters/) available in nixpkgs 
2) Create adapters and configurations based on [those in the nvim-dap wiki](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#ansible)
3) Decide on a scheme to spin up a DAP based on FileType, and potentially create a popup which allows someone to choose which server they would like to use (you can't just load them all like with LSPs)

**Comment by dundalek** [comment]
This makes sense and sounds useful.
However, I would consider it out of scope of this plugin as I personally don't use and have no experience with nvim-dap.
Perhaps someone else could take it on and create a new plugin (using lazy-lsp as inspiration).
