### ISSUE TITLE
rnix removed because it is unmaintained

### ISSUE THREAD

**Issue by pigeonhands** [dundalek/lazy-lsp.nvim#46]
Currently, editing a nix file gives an error about `rnix` being unmaintained
```
[ERROR][2024-08-30 13:12:42] .../vim/lsp/rpc.lua:770	"rpc"	"nix-shell"	"stderr"	"error:\n       
… while calling the 'derivationStrict' builtin\n\n         at /builtin/derivation.nix:9:12: (source not available)\n\n       
… while evaluating derivation 'shell'\n         whose name attribute is located at /nix/store/5z81la6av4j0ckp0w1949lxiwjyyykks-source/pkgs/stdenv/generic/make-derivation.nix:333:7\n\n       
… while evaluating attribute 'buildInputs' of derivation 'shell'\n\n         at /nix/store/5z81la6av4j0ckp0w1949lxiwjyyykks-source/pkgs/stdenv/generic/make-derivation.nix:380:7:\n\n          379|       depsHostHost                = elemAt (elemAt dependencies 1) 0;\n          380|       buildInputs                 = elemAt (elemAt dependencies 1) 1;\n             |       ^\n          381|       depsTargetTarget            = elemAt (elemAt dependencies 2) 0;\n\n       
error: 'rnix-lsp' has been removed as it is unmaintained\n"
```

Also means formatting does not work currently. Is there a way to manually specify a lsp/formatter and completely override `preferred_servers`? `nixfmt` may be a replacement.

**Comment by pigeonhands** [comment]
Maybe an option to avoid lsp servers being removed and breaking setups is to have a flake.nix in this repository re-exporting nixpkgs derivations for the supported lsp servers. Then you could default the lsp execute to `nix run git+https://github.com/dundalek/lazy-lsp.nvim.git#<lsp-server> --command <lsp-server>`

Though to actually pin the nixpkgs  to a known version means it not being the same as the system nixpkgs and causing some duplication on the system. Though there may be a way around that with overrides?

**Comment by dundalek** [comment]
In my view it is unfortunate when things get removed, but if a package is not considered to be worthy for nixpkgs, then I probably don't want to put myself into a position to maintain it.

In case you find an alternative configuration, we could add it as a recipe to [docs](https://github.com/dundalek/lazy-lsp.nvim/blob/master/notes.md).

**Comment by dundalek** [comment]
Closing as there does not seem to any actionable item. Feel free to open a new issue if something else comes up.
