### ISSUE TITLE
eslint server doesn't start

### ISSUE THREAD

**Issue by deansallinen** [dundalek/lazy-lsp.nvim#50]
`:LspInfo` for the eslint client shows 'Unable to find executable. Please check your path and ensure the server is installed'

`lsp.log` has this: 
```
[ERROR][2024-09-06 14:15:45] .../vim/lsp/rpc.lua:770	"rpc"	"nix-shell"	"stderr"	"error:\n       … while calling the 'derivationStrict' builtin\n\n         at /builtin/derivation.nix:9:12: (source not available)\n\n       … while evaluating derivation 'shell'\n         whose name attribute is located at /nix/store/6q9ka6rniissks2k8620nvy3gnvl7nph-nixos/nixos/pkgs/stdenv/generic/make-derivation.nix:336:7\n\n       … while evaluating attribute 'buildInputs' of derivation 'shell'\n\n         at /nix/store/6q9ka6rniissks2k8620nvy3gnvl7nph-nixos/nixos/pkgs/stdenv/generic/make-derivation.nix:383:7:\n\n          382|       depsHostHost                = elemAt (elemAt dependencies 1) 0;\n          383|       buildInputs                 = elemAt (elemAt dependencies 1) 1;\n             |       ^\n          384|       depsTargetTarget            = elemAt (elemAt dependencies 2) 0;\n\n       error: Alias eslint is still in node-packages.nix\n"
```

So I started poking around in `servers.lua` for eslint and when I looked on search.nixos.org for `nodePackages.vscode-langservers-extracted` it didn't appear: https://search.nixos.org/packages?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=nodePackages.vscode-langservers-extracted

It looks like it no longer has the `nodePackages` namespace: https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/development/tools/language-servers/vscode-langservers-extracted/default.nix#L38

Changing
```lua
  eslint = {
    "nodePackages.vscode-langservers-extracted",
    "nodePackages.eslint"
  },
```
to
```lua
  eslint = {
    "vscode-langservers-extracted",
  },
```
worked to initialize `eslint`. 

Might need to make an update to remove the namespace?

Oddly enough `nodePackages.vscode-langservers-extracted` seems to work fine for `cssls`, `jsonls`, and `html` .

I'm not sure why removing `nodePackages.eslint` was required, maybe a conflict?

**Comment by deansallinen** [comment]
So on further testing, it seems like leaving the `nodePackages` namespace in place is fine, but having `nodePackages.eslint` in the table causes the eslint client to quit. Removing `nodePackages.eslint` allows the client to attach. 

Tested on an existing project with a large `eslint.config.js` and a fresh project with a blank `.eslintrc`

**Comment by dundalek** [comment]
It looks like there is a trend of changing the packages to drop the `nodePackages` prefix: https://github.com/NixOS/nixpkgs/pull/322597

I think I would probably still keep `eslint` to have a global fallback so that it still works when cloning a repo without running `npm install`, otherwise one gets `Failed to load eslint library` error.
