### ISSUE TITLE
Drop nodePackages prefix when possible

### ISSUE THREAD

**Issue by dundalek** [dundalek/lazy-lsp.nvim#52]
There is trend in nixpkgs of changing packaging of node packages without the `nodePackages` prefix which leads to lead to broken servers like in https://github.com/dundalek/lazy-lsp.nvim/issues/50. So far I also changed it for another vscode extracted servers: https://github.com/dundalek/lazy-lsp.nvim/commit/01272d5ca9c08d70c489c270d86b73ca565bc319

It might be worth to go through the packages proactively rather than users encountering breakage and needing to report an issue.

Task: For each package with `nodePackages` verify that there is a corresponding package without the prefix on https://search.nixos.org/ and drop the prefix if there is.

**Comment by dundalek** [comment]
@deansallinen Would you be interesting in helping out?

**Comment by deansallinen** [comment]
Sure, I don't mind taking a look at this

**Comment by deansallinen** [comment]
These all have the `nodePackages` prefix dropped in the 24.05 channel:
- `dockerfile-language-server-nodejs`
- `tailwindcss-language-server`
- `typescript`
- `vim-language-server`

And in the Unstable channel, these also drop the prefix:
- `bash-language-server`
- `diagnostic-languageserver`
- `intelephense`
- `svelte-language-server`
- `typescript-language-server`
- `vue-language-server`

I'm still learning nix, but it seems like `nix-shell -p` will reference packages in the Unstable channel, so these could all be candidates to drop the prefix.

**Comment by dundalek** [comment]
Makes sense, I also recommend using [unstable](https://github.com/dundalek/lazy-lsp.nvim?tab=readme-ov-file#versions).
